# Generated by Django 4.2.27 on 2025-12-24 18:07

import apps.licenses.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название лицензии')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер лицензии')),
                ('category', models.CharField(choices=[('surveying', 'Изыскания и проектирование'), ('construction', 'Строительство'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.licenses.models.license_upload_to, verbose_name='Файл')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('valid_until', models.DateField(verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'db_table': 'licenses',
                'ordering': ['-issued_date'],
            },
        ),
    ]
