# Generated by Django 4.2.27 on 2025-12-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Действует до'),
        ),
    ]
