# Generated by Django 4.2.27 on 2025-12-23 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('course_assigned', 'Course Assigned'), ('exam_available', 'Exam Available'), ('protocol_ready', 'Protocol Ready'), ('certificate_issued', 'Certificate Issued'), ('pdek_signature_request', 'PDEK Signature Request'), ('exam_passed', 'Exam Passed'), ('exam_failed', 'Exam Failed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='notificatio_user_id_cba35e_idx')],
            },
        ),
    ]
