# Generated by Django 4.2.27 on 2025-12-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('direction', models.CharField(blank=True, choices=[('construction', 'Строительство и проектирование'), ('engineering', 'Инженерные изыскания'), ('education', 'Обучение'), ('safety', 'Промышленная безопасность'), ('other', 'Другое')], max_length=50, verbose_name='Направление')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('read', 'Прочитано'), ('replied', 'Отвечено'), ('archived', 'Архивировано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
