# Generated by Django 4.2.16 on 2026-01-14 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('file', models.FileField(help_text='Template file', upload_to='certificates/templates/')),
                ('is_active', models.BooleanField(default=True, help_text='Is template active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificate_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded certificate file', null=True, upload_to='certificates/files/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the file was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Admin who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Certificate template used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate'),
        ),
    ]
