# Generated by Django 4.2.27 on 2025-12-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('protocol_sign', 'Protocol Signing'), ('registration', 'Registration'), ('password_reset', 'Password Reset'), ('verification', 'General Verification')], default='verification', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sms_verification_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_verified'], name='sms_verific_phone_5a3563_idx'), models.Index(fields=['expires_at'], name='sms_verific_expires_f3a895_idx')],
            },
        ),
    ]
