# Generated by Django 4.2.27 on 2025-12-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('courses', '0002_category_alter_course_status_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='final_test',
            field=models.ForeignKey(blank=True, help_text='Final test for course completion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_courses', to='tests.test'),
        ),
        migrations.CreateModel(
            name='CourseCompletionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_verification', to='courses.courseenrollment')),
            ],
            options={
                'db_table': 'course_completion_verifications',
            },
        ),
    ]
