# Generated by Django 4.2.27 on 2025-12-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_final_test_coursecompletionverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('exam_available', 'Exam Available'), ('exam_passed', 'Exam Passed'), ('pending_pdek', 'Pending PDEK Review'), ('completed', 'Completed'), ('failed', 'Failed'), ('annulled', 'Annulled')], default='assigned', max_length=20),
        ),
    ]
