# Generated by Django 4.2.27 on 2025-12-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('passing_score', models.IntegerField(default=80, help_text='Minimum score to pass (percentage)')),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum attempts allowed')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='courses.course')),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('short_answer', 'Short Answer')], max_length=20)),
                ('text', models.TextField()),
                ('options', models.JSONField(default=list, help_text='List of answer options with is_correct flag')),
                ('order', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=1, help_text='Question weight for scoring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order', 'id'],
                'unique_together': {('test', 'order')},
            },
        ),
    ]
