# Generated by Django 4.2.27 on 2025-12-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
    ]
