# Generated by Django 4.2.16 on 2026-01-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_add_language_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list, help_text='List of answer options with is_correct flag. Options can have text, text_kz, text_en fields for multilingual support.'),
        ),
    ]
