# Generated by Django 4.2.27 on 2025-12-23 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('exam_date', models.DateTimeField()),
                ('score', models.FloatField()),
                ('passing_score', models.FloatField()),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=10)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('pending_pdek', 'Pending PDEK'), ('signed_members', 'Signed by Members'), ('signed_chairman', 'Signed by Chairman'), ('rejected', 'Rejected'), ('annulled', 'Annulled')], default='generated', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='exams.testattempt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'protocols',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('chairman', 'Chairman')], max_length=10)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='protocols.protocol')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'protocol_signatures',
                'unique_together': {('protocol', 'signer')},
            },
        ),
    ]
