# Generated by Django 4.2.27 on 2025-12-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_final_test_coursecompletionverification'),
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='enrollment',
            field=models.ForeignKey(blank=True, help_text='Enrollment for course completion protocols', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='courses.courseenrollment'),
        ),
    ]
